---
title: Highcharts Spiderplot
author: Iaroslav Domin
date: '2019-02-19'
slug: hc-spider
categories: []
tags: []
description: Desc
meta_img: /images/image.jpg
---


```{r message=FALSE, warning=FALSE}
library(readr)
library(ggplot2)
sumldiam <- read_csv("data/sumldiam.csv")
```



```{r dev='CairoPNG', fig.asp=.8, fig.width=10}
ggplot(sumldiam, aes(x, y, group = SUBJ, color = BOR)) +
    theme_minimal() +
    geom_point(size = 1.1) +
    geom_line(alpha = .9, size = 1) +
    scale_color_manual(
        "BOR: ",
        values = c("CR" = "#00aedb", "PR" = "#00b159",
                   "SD" = "#ffc425", "PD" = "#d11141",
                   "NE" = "#545454"),
        guide  = guide_legend(order = 1)
    ) +
    geom_hline(yintercept = 0, color = "gray75") +
    labs(y = NULL,
         x = "Week") +
    theme(panel.grid = element_blank(),
          legend.direction = "horizontal",
          legend.position = "top",
          legend.justification = "left",
          text = element_text(size = 14),
          plot.title = element_text(size = 17, face = "bold")) +
    ggtitle("Change in Target Lesions over Time [%]") +
    NULL
```

